/* user */
export const AUTH = 'AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FETCH_TENANTS_REQUEST = 'FETCH_TENANTS_REQUEST';
export const FETCH_TENANTS_SUCCESS = 'FETCH_TENANTS_SUCCESS';
export const FETCH_TENANTS_FAILURE = 'FETCH_TENANTS_FAILURE';

/* tenant */
export const TENANT_AUTH_REQUEST = 'TENANT_AUTH_REQUEST';
export const TENANT_AUTH_SUCCESS = 'TENANT_AUTH_SUCCESS';
export const TENANT_AUTH_FAILURE = 'TENANT_AUTH_FAILURE';
export const FETCH_SUBJECT_MEDIA_REQUEST = 'FETCH_SUBJECT_MEDIA_REQUEST';
export const FETCH_SUBJECT_MEDIA_SUCCESS = 'FETCH_SUBJECT_MEDIA_SUCCESS';
export const FETCH_SUBJECT_MEDIA_FAILURE = 'FETCH_SUBJECT_MEDIA_FAILURE';
