/* user */
export const AUTH = 'AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FETCH_TENANTS_REQUEST = 'FETCH_TENANTS_REQUEST';
export const FETCH_TENANTS_SUCCESS = 'FETCH_TENANTS_SUCCESS';
export const FETCH_TENANTS_FAILURE = 'FETCH_TENANTS_FAILURE';

/* tenant */
export const TENANT_AUTH_SUCCESS = 'TENANT_AUTH_SUCCESS';
export const GET_TENANT_SUCCESS = 'GET_TENANT_SUCCESS';
export const GET_SUBJECT_SUCCESS = 'GET_SUBJECT_SUCCESS';
export const SUBJECT_LOAD_MORE_SUCCESS = 'SUBJECT_LOAD_MORE_SUCCESS';
